---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cerebellum-edge-node-1
  labels:
    app: cerebellum-edge-node-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cerebellum-edge-node-1
  template:
    metadata:
      labels:
        app: cerebellum-edge-node-1
    spec:
      nodeName: edge-node-1
      containers:
      - name: cerebellum
        image: 10.112.134.196:5000/iai/cerebellumcontroller 
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
          - name: dbfile
            value: /db/route.sqlite
          - name: port
            value: "3000"
          - name: filebase
            value: /data/
          - name: redisaddr
            value: redis-svc-cloud-node.iai.svc.cluster.local:6379
          - name: nodename
            valueFrom:
              fieldRef: 
                fieldPath:
                  spec.nodeName
          - name: brainaddr
            value: ws://10.112.134.196:8080/api/brainController/ws
        volumeMounts:
          - mountPath: "/data"
            name: "data"
          - mountPath: "/db"
            name: db
      volumes:
        - name: data
          hostPath: 
            path: /data/cerebellum/data/
            type: DirectoryOrCreate
        - name: db
          hostPath: 
            path: /data/cerebellum/conf/
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: cerebellum-svc-edge-node-1
  namespace: iai
  labels:
    app: cerebellum-svc-edge-node-1
spec:
  selector:
    app: cerebellum-edge-node-1
  ports:
    - name: cerebellum
      protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment-edge-node-1
  labels:
    app: redis-edge-node-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-edge-node-1
  template:
    metadata:
      labels:
        app: redis-edge-node-1
    spec:
      nodeName: edge-node-1
      containers:
      - name: redis
        image: redis
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-svc-edge-node-1
  namespace: iai
  labels:
    app: redis-svc-edge-node-1
spec:
  selector:
    app: redis-edge-node-1
  ports:
    - name: redis
      protocol: TCP
      port: 6379
      targetPort: 6379
  type: ClusterIP